sudo: required
addons:
  chrome: stable
language: node_js
node_js:
    - "lts/*"
cache:
    directories:
        - node_modules
git:
    depth: 3
# before_script:
  # - export DISPLAY=:99.0
  # - sh -e /etc/init.d/xvfb start
install:
  - npm install
script:
  - npm run ci